services:
  # G1GC (Mimicking run-g1gc.sh --profile high)
  visualizer-g1:
    build: .
    image: gc-visualizer:latest
    container_name: gc-v-g1gc
    ports:
      - "8081:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xms1g -Xmx2g -Xlog:gc*:file=logs/g1gc-high.log:time,uptime,level,tags
    restart: unless-stopped

  # Generational ZGC (Mimicking run-zgc.sh --profile high)
  visualizer-zgc-gen:
    build: .
    image: gc-visualizer:latest
    container_name: gc-v-zgc-gen
    ports:
      - "8082:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - JAVA_OPTS=-XX:+UseZGC -XX:+ZGenerational -Xms1g -Xmx2g -Xlog:gc*:file=logs/zgc-gen-high.log:time,uptime,level,tags
    restart: unless-stopped

  # Plain ZGC (Non-Generational comparison)
  visualizer-zgc-plain:
    build: .
    image: gc-visualizer:latest
    container_name: gc-v-zgc-plain
    ports:
      - "8083:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - JAVA_OPTS=-XX:+UseZGC -XX:-ZGenerational -Xms1g -Xmx2g -Xlog:gc*:file=logs/zgc-plain-high.log:time,uptime,level,tags
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: gc-v-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    depends_on:
      - visualizer-g1
      - visualizer-zgc-gen
      - visualizer-zgc-plain

  grafana:
    image: grafana/grafana:latest
    container_name: gc-v-grafana
    ports:
      - "3000:3000"
    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=gcviz
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/gc-comparison.json
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    restart: unless-stopped
    depends_on:
      - prometheus