{
 "title": "GC Logs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "G1GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "G1GC - GC Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{gc_type=\"G1GC\", log_source=\"gc\"}"
    }
   ]
  },
  {
   "title": "G1GC - App Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{gc_type=\"G1GC\", log_source=\"app\"}"
    }
   ]
  },
  { "title": "ZGC Generational", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "ZGC Gen - GC Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{gc_type=\"ZGC Generational\", log_source=\"gc\"}"
    }
   ]
  },
  {
   "title": "ZGC Gen - App Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{gc_type=\"ZGC Generational\", log_source=\"app\"}"
    }
   ]
  },
  { "title": "ZGC Non-Generational", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "ZGC Non-Gen - GC Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{gc_type=\"ZGC Non-Generational\", log_source=\"gc\"}"
    }
   ]
  },
  {
   "title": "ZGC Non-Gen - App Log",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "{gc_type=\"ZGC Non-Generational\", log_source=\"app\"}"
    }
   ]
  }
 ]
}